import Head from "next/head";
import { Be_Vietnam_Pro } from "next/font/google";

import { Contenedor } from "@/components/Contenedor";
import { Wizard } from "@/components/Wizard";
import { useContext, useEffect, useState } from "react";
import {
  IDatosClinicos,
  IDatosPersonales,
} from "@/components/Wizard/Datos.types";
import { DatosContext } from "@/context/DatosFormContext";
import { AutenticacionOTP } from "@/components/OTP/AutenticacionOTP";
import { ConstructorForm } from "@/interfaces/ConstructorForm";

const tipografia = Be_Vietnam_Pro({
  subsets: ["latin"],
  weight: "300",
});

export default function HomePage() {
  const { datos, setDatos } = useContext(DatosContext);
  const [otp, setOtp] = useState(true);
  const [errorOtp, setErrorOtp] = useState(false);
  const [valueOtp, setValueOtp] = useState("");
  const [camposForm, setCamposForm] = useState<ConstructorForm>();
  const [dataForm, setDataForm] = useState<IDatosPersonales & IDatosClinicos>({
    ...datos,
  });

  const handleClick = () => {
    const codigo = "052023";
    setErrorOtp(!(codigo === valueOtp));
    setOtp(!(codigo === valueOtp));
    console.log(valueOtp);
  };

  const obtenerFormulario = async () => {
    const response = await fetch(
      "https://pip-preconsulta.vercel.app/datos.json"
    );
    const result: ConstructorForm = await response.json();
    setCamposForm(result);
  };

  useEffect(() => {
    obtenerFormulario();
  }, []);

  return (
    <>
      <Head>
        <title>PIP - Programa inteligente de pre-consulta</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={tipografia.className}>
        {otp ? (
          <AutenticacionOTP
            onChange={(e) => setValueOtp(e)}
            onClick={() => handleClick()}
            error={errorOtp}
          />
        ) : (
          <Contenedor>
            <Wizard onSubmit={(e) => setDataForm(e)} camposForm={camposForm} />
          </Contenedor>
        )}
        {/* Hecho con tecnología de Biofile */}
      </main>
    </>
  );
}
